name: "gitstream"
description: "Check your Node application for vulnerabilties using gitstream"
author: "Ofer"
branding:
  icon: "alert-triangle"
  color: "yellow"
inputs:
  command:
    description: "Which command to run, defaults to parse"
    default: parse
  lanes:
    description: "Lanes"
runs:
  using: "docker"
  image: "docker://gitstream/parser:0.1.7"
  args:
    - ${{ inputs.lanes }}
